services:
  redis:
    image: redis:8.0.2-alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_volume:/data
    ports:
      - '${REDIS_PORT}:6379'
    restart: unless-stopped

  redisinsight:
    image: redislabs/redisinsight:2.70
    ports:
      - '5540:5540'
    restart: unless-stopped

volumes:
  redis_volume:
